# Read the Docs configuration file
version: 2

environment:
  UV_PYTHON: "3.12"

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
  commands:
    - pip install uv
    - uv sync --all-groups --all-extras
    - uv run python -m sphinx docs $READTHEDOCS_OUTPUT/html -b html -W

sphinx:
  builder: html
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
